services:
  db:
    container_name: order-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: order
      MYSQL_USER: order
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  testdb:
    container_name: order-test-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: order
      MYSQL_USER: order
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql-test-data:/var/lib/mysql
    ports:
      - "3307:3306"