name: Java CI with Gradle (Groovy)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_NAME: order
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USER -p$DB_PASSWORD
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: temurin
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: build
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: Build Artifacts
          path: |
            **/build/reports
